name: Build CUDA Containers

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      cuda_version:
        description: 'CUDA version to build'
        required: true
        default: '12.3.1'
        type: choice
        options:
          - '12.3.1'
          - '12.2.2'
          - '12.1.1'
          - '11.8.0'
      rhel_version:
        description: 'RHEL version'
        required: true
        default: '9.3'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        include:
          - cuda_version: "12.3.1"
          - cuda_version: "12.2.2"
          - cuda_version: "12.1.1"
          - cuda_version: "11.8.0"
        exclude:
          - cuda_version: ${{ github.event_name != 'workflow_dispatch' && '12.2.2' || '' }}
          - cuda_version: ${{ github.event_name != 'workflow_dispatch' && '12.1.1' || '' }}
          - cuda_version: ${{ github.event_name != 'workflow_dispatch' && '11.8.0' || '' }}
          - cuda_version: ${{ github.event_name == 'workflow_dispatch' && inputs.cuda_version != '12.3.1' && '12.3.1' || '' }}
          - cuda_version: ${{ github.event_name == 'workflow_dispatch' && inputs.cuda_version != '12.2.2' && '12.2.2' || '' }}
          - cuda_version: ${{ github.event_name == 'workflow_dispatch' && inputs.cuda_version != '12.1.1' && '12.1.1' || '' }}
          - cuda_version: ${{ github.event_name == 'workflow_dispatch' && inputs.cuda_version != '11.8.0' && '11.8.0' || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=cuda${{ matrix.cuda_version }}
            type=raw,value=cuda${{ matrix.cuda_version }}-rhel${{ github.event_name == 'workflow_dispatch' && inputs.rhel_version || '9.3' }}
            type=semver,pattern={{version}}-cuda${{ matrix.cuda_version }}
            type=semver,pattern={{version}}-cuda${{ matrix.cuda_version }}-rhel${{ github.event_name == 'workflow_dispatch' && inputs.rhel_version || '9.3' }}
            type=sha,prefix=cuda${{ matrix.cuda_version }}-

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            RHEL_VERSION=${{ github.event_name == 'workflow_dispatch' && inputs.rhel_version || '9.3' }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
            LICENSE
          body: |
            CUDA ${{ matrix.cuda_version }} container image for RHEL ${{ github.event_name == 'workflow_dispatch' && inputs.rhel_version || '9.3' }}
            
            Container images:
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cuda${{ matrix.cuda_version }}`
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cuda${{ matrix.cuda_version }}-rhel${{ github.event_name == 'workflow_dispatch' && inputs.rhel_version || '9.3' }}` 